// Generated by scripts/version.mjs; do not edit. Change it with `npm run version:set <version>`.

/**
 * The GloSharp.Cli version this release of @glosharp/core was built and tested
 * with. The npm packages and the CLI are released together at one version.
 */
export const EXPECTED_CLI_VERSION = '0.1.0-alpha.2'
