#!/usr/bin/env node
// The one place Glo#'s release version is read and written.
//
// Source of truth: <Version> in src/Directory.Build.props (GloSharp.Core,
// GloSharp.Cli and `glosharp --version` take it from there). Everything else is
// stamped from it and checked against it:
//
//   - "version" of every published npm package (packages/*)
//   - their @glosharp/* dependency ranges (exact pins: the packages ship in lockstep)
//   - the matching entries in package-lock.json
//   - packages/glosharp/src/version.generated.ts (the CLI version @glosharp/core
//     expects; see compat.ts)
//
// Usage:
//   node scripts/version.mjs                    print the current version
//   node scripts/version.mjs set <version>      stamp <version> everywhere
//   node scripts/version.mjs check [--tag vX]   fail if anything has drifted (and,
//                                               with --tag, if the tag doesn't match)
//   node scripts/version.mjs info [--tag vX]    check, then print key=value lines for
//                                               $GITHUB_OUTPUT (version, tag, dist-tag,
//                                               prerelease)
//
// npm scripts: `npm run version:set <version>`, `npm run version:check`.
// No dependencies beyond Node itself.

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const PROPS = join(root, 'src', 'Directory.Build.props')
const LOCK = join(root, 'package-lock.json')
const GENERATED = join(root, 'packages', 'glosharp', 'src', 'version.generated.ts')
const DEP_FIELDS = ['dependencies', 'peerDependencies', 'optionalDependencies', 'devDependencies']

// semver.org's grammar, minus nothing: numeric identifiers without leading zeros.
const NUM = '0|[1-9]\\d*'
const IDENT = `(?:${NUM}|\\d*[A-Za-z-][0-9A-Za-z-]*)`
const SEMVER = new RegExp(
  `^(${NUM})\\.(${NUM})\\.(${NUM})(?:-(${IDENT}(?:\\.${IDENT})*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$`,
)
const VERSION_ELEMENT = /<Version>([^<]*)<\/Version>/

const rel = (file) => relative(root, file).replaceAll('\\', '/')

export function parseVersion(version) {
  const m = SEMVER.exec(version)
  if (!m) return null
  return { major: +m[1], minor: +m[2], patch: +m[3], prerelease: m[4] ? m[4].split('.') : [], build: m[5] }
}

/** npm dist-tag for a version: the prerelease id (alpha, beta, rc…) or `latest`. */
export function distTag(version) {
  const parsed = parseVersion(version)
  if (!parsed) throw new Error(`${version} is not a semver version`)
  if (parsed.prerelease.length === 0) return 'latest'
  const id = parsed.prerelease[0]
  // npm refuses dist-tags that parse as a version range (e.g. "1").
  return /^\d+$/.test(id) ? 'next' : id
}

function readJson(file) {
  return JSON.parse(readFileSync(file, 'utf8'))
}

/** Keep the file's existing indentation and trailing newline. */
function writeJson(file, value) {
  const text = readFileSync(file, 'utf8')
  const indent = /^[ \t]+(?=")/m.exec(text)?.[0] ?? '  '
  writeFileSync(file, JSON.stringify(value, null, indent) + (text.endsWith('\n') ? '\n' : ''))
}

function readPropsVersion() {
  const m = VERSION_ELEMENT.exec(readFileSync(PROPS, 'utf8'))
  if (!m) throw new Error(`${rel(PROPS)} has no <Version> element`)
  return m[1].trim()
}

/** Published npm packages: every non-private packages/* directory. */
function publishedPackages() {
  return readdirSync(join(root, 'packages'))
    .map((name) => join(root, 'packages', name))
    .filter((dir) => existsSync(join(dir, 'package.json')))
    .map((dir) => ({ dir, file: join(dir, 'package.json'), json: readJson(join(dir, 'package.json')) }))
    .filter((pkg) => !pkg.json.private)
}

function generatedSource(version) {
  return `// Generated by scripts/version.mjs; do not edit. Change it with \`npm run version:set <version>\`.

/**
 * The GloSharp.Cli version this release of @glosharp/core was built and tested
 * with. The npm packages and the CLI are released together at one version.
 */
export const EXPECTED_CLI_VERSION = '${version}'
`
}

function set(version) {
  if (!parseVersion(version)) throw new Error(`"${version}" is not a semver version (e.g. 0.2.0-alpha.1)`)
  if (parseVersion(version).build) throw new Error('build metadata (+…) is not allowed in a release version')

  const props = readFileSync(PROPS, 'utf8')
  writeFileSync(PROPS, props.replace(VERSION_ELEMENT, `<Version>${version}</Version>`))

  const packages = publishedPackages()
  const names = new Set(packages.map((p) => p.json.name))
  const lock = readJson(LOCK)

  for (const pkg of packages) {
    pkg.json.version = version
    for (const field of DEP_FIELDS) {
      for (const dep of Object.keys(pkg.json[field] ?? {})) {
        if (names.has(dep)) pkg.json[field][dep] = version
      }
    }
    writeJson(pkg.file, pkg.json)

    // Mirror into package-lock.json so `npm ci` stays in sync without a network round trip.
    const entry = lock.packages?.[rel(pkg.dir)]
    if (entry) {
      entry.version = version
      for (const field of DEP_FIELDS) {
        for (const dep of Object.keys(entry[field] ?? {})) {
          if (names.has(dep)) entry[field][dep] = version
        }
      }
    }
  }
  writeJson(LOCK, lock)
  writeFileSync(GENERATED, generatedSource(version))

  console.log(`Set version ${version} in:`)
  for (const file of [PROPS, ...packages.map((p) => p.file), LOCK, GENERATED]) console.log(`  ${rel(file)}`)
}

/** Every inconsistency, as human-readable strings. Empty when all is well. */
function problems(tag) {
  const version = readPropsVersion()
  const out = []
  const parsed = parseVersion(version)
  if (!parsed) out.push(`${rel(PROPS)}: <Version>${version}</Version> is not a semver version`)
  else if (parsed.build) out.push(`${rel(PROPS)}: <Version> must not carry build metadata (+${parsed.build})`)

  // A <Version> in a project file would silently override the shared one.
  for (const project of ['GloSharp.Core', 'GloSharp.Cli']) {
    const csproj = join(root, 'src', project, `${project}.csproj`)
    if (/<(Version|VersionPrefix|VersionSuffix|PackageVersion)>/.test(readFileSync(csproj, 'utf8'))) {
      out.push(`${rel(csproj)}: sets its own version; remove it (the version lives in ${rel(PROPS)})`)
    }
  }

  const packages = publishedPackages()
  const names = new Set(packages.map((p) => p.json.name))
  const lock = readJson(LOCK)
  for (const pkg of packages) {
    const where = rel(pkg.file)
    if (pkg.json.version !== version) out.push(`${where}: version is ${pkg.json.version}, expected ${version}`)
    for (const field of DEP_FIELDS) {
      for (const [dep, range] of Object.entries(pkg.json[field] ?? {})) {
        if (names.has(dep) && range !== version) out.push(`${where}: ${field}.${dep} is ${range}, expected ${version}`)
      }
    }
    const entry = lock.packages?.[rel(pkg.dir)]
    if (!entry) {
      out.push(`${rel(LOCK)}: no entry for ${rel(pkg.dir)} (run npm install)`)
      continue
    }
    if (entry.version !== version) out.push(`${rel(LOCK)}: ${rel(pkg.dir)} version is ${entry.version}, expected ${version}`)
    for (const field of DEP_FIELDS) {
      for (const [dep, range] of Object.entries(entry[field] ?? {})) {
        if (names.has(dep) && range !== version) {
          out.push(`${rel(LOCK)}: ${rel(pkg.dir)} ${field}.${dep} is ${range}, expected ${version}`)
        }
      }
    }
  }

  const generated = existsSync(GENERATED) ? readFileSync(GENERATED, 'utf8') : ''
  if (generated !== generatedSource(version)) out.push(`${rel(GENERATED)}: out of date`)

  if (tag !== undefined) {
    const expected = `v${version}`
    if (tag !== expected) {
      out.push(`tag ${tag} does not match the version in ${rel(PROPS)} (${version}); expected tag ${expected}`)
    }
  }
  return { version, problems: out }
}

function check(tag) {
  const result = problems(tag)
  if (result.problems.length > 0) {
    console.error(`Version drift (source of truth: ${rel(PROPS)} = ${result.version}):`)
    for (const p of result.problems) console.error(`  - ${p}`)
    if (tag !== undefined && tag !== `v${result.version}`) {
      console.error(
        `To release ${tag}, run \`npm run version:set ${tag.replace(/^v/, '')}\`, commit, and tag that commit.`,
      )
    } else {
      console.error(`Fix with: npm run version:set ${result.version}`)
    }
    process.exit(1)
  }
  return result.version
}

function main(argv) {
  const [command = 'get', ...rest] = argv
  let tag
  const positional = []
  for (let i = 0; i < rest.length; i++) {
    if (rest[i] === '--tag') {
      tag = rest[++i]
      if (!tag) throw new Error('--tag needs a value')
    } else if (rest[i].startsWith('--tag=')) {
      tag = rest[i].slice('--tag='.length)
    } else {
      positional.push(rest[i])
    }
  }
  // Accept refs/tags/v1.2.3 as well as v1.2.3.
  if (tag !== undefined) tag = tag.replace(/^refs\/tags\//, '')

  switch (command) {
    case 'get':
      console.log(readPropsVersion())
      break
    case 'set':
      if (positional.length !== 1) throw new Error('usage: version.mjs set <version>')
      set(positional[0].replace(/^v/, ''))
      check()
      break
    case 'check': {
      const version = check(tag)
      console.log(`Version ${version} is consistent${tag ? ` and matches tag ${tag}` : ''}.`)
      break
    }
    case 'info': {
      const version = check(tag)
      const parsed = parseVersion(version)
      console.log(`version=${version}`)
      console.log(`tag=v${version}`)
      console.log(`dist-tag=${distTag(version)}`)
      console.log(`prerelease=${parsed.prerelease.length > 0}`)
      break
    }
    default:
      throw new Error(`unknown command "${command}" (expected get, set, check or info)`)
  }
}

try {
  main(process.argv.slice(2))
} catch (error) {
  console.error(`version: ${error.message}`)
  process.exit(1)
}
